### ISSUE TITLE
Clean code tests are throwing a NoSuchElementException

### ISSUE THREAD

**Issue by d-eder** [cloudflightio/archunit-cleancode-verifier#11]
The following tests are throwing a NoSuchElementException:
* methods_that_are_transactional_should_access_other_transactional_methods_or_repositories
* controller_methods_should_not_access_more_than_one_transactional_method

see [stacktrace.txt](https://github.com/cloudflightio/archunit-cleancode-verifier/files/9495315/stacktrace.txt)

It seems that this happens when you are using `enum.values()`.

## Code to reproduce
```
@AnalyzeClasses(packagesOf = [TmpArchitectureTest::class])
class TmpArchitectureTest: AbstractCleanCodeTest()

class SomeService() {
    fun something() {
        val enumValues = Test.values()
        println(enumValues)
    }
}

enum class Test {
    Test1, Test2;
}

@RestController
class SomeController(private val someService: SomeService) {
    fun test() {
        someService.something()
    }
}
```

**Comment by klu2** [comment]
this is already solved with version 0.1.1
#12 added another unit-test the ensure that
