### ISSUE TITLE
nullable_flag_of_kotlin_needs_to_match_jpa_specification wrong violations for optional relationship annotations

### ISSUE THREAD

**Issue by rmaunz** [cloudflightio/archunit-cleancode-verifier#15]
currently, the nullable_flag_of_kotlin_needs_to_match_jpa_specification test does not consider the optional flag of relationship annotations (except @OneToMany and @ManyToMany/any collection types).

### How to reproduce:
create an entity with the following relationship:
```
@ManyToOne(optional = false)
var someEntity: SomeEntity,
```

Right now this produces the following error (which it should not):
`someEntity is nullable in the DB, but the kotlin field is not nullable`

**Comment by klu2** [comment]
fixed with #17

**Comment by klu2** [comment]
in any ways, you should add the `@NotNull` annotation on `@ManyToOne` annotations as well
